const $=s=>document.querySelector(s), min=t=>{const [h,m]=t.split('.').map(Number);return h*60+m}, fmt=n=>`${String(Math.floor(n/60)%24).padStart(2,'0')}.${String(n%60).padStart(2,'0')}`;
const state={events:[],picked:new Set(JSON.parse(localStorage.getItem('tsp-day2')||'[]'))};
const overlap=(a,b)=>a.start<b.end&&b.start<a.end;
function build(data){state.events=data.stages.flatMap((s,si)=>s.events.map(([time,artist],i)=>{const start=min(time), next=s.events[i+1]?.[0];return{id:`${si}-${i}`,stage:s.name,time,artist,start,end:next?min(next):1500}}));}
function render(){const groups=Object.groupBy(state.events,e=>e.time);$('#timeline').innerHTML=Object.entries(groups).sort(([a],[b])=>min(a)-min(b)).map(([time,items])=>`<div class="slot"><time class="rail">${time}</time><div class="slot-events">${items.map(e=>{const chosen=state.picked.has(e.id);const blocked=!chosen&&[...state.picked].some(id=>{const q=state.events.find(x=>x.id===id);return q&&overlap(e,q)});return `<button class="event ${chosen?'chosen':''} ${blocked?'blocked':''}" data-id="${e.id}" ${blocked?'disabled':''} aria-pressed="${chosen}"><small>${e.stage} · ${time}–${fmt(e.end)}</small><strong>${e.artist}</strong>${blocked?'<em>Bentrok</em>':''}</button>`}).join('')}</div></div>`).join('');document.querySelectorAll('.event').forEach(b=>b.onclick=()=>{state.picked.has(b.dataset.id)?state.picked.delete(b.dataset.id):state.picked.add(b.dataset.id);save();render()});const picked=state.events.filter(e=>state.picked.has(e.id)).sort((a,b)=>a.start-b.start);$('#count').textContent=`${picked.length} set dipilih`;$('#detail').textContent=picked.length?`${fmt(picked[0].start)}–${fmt(picked.at(-1).end)} · set bentrok terkunci`:'Pilih set untuk mulai.';$('#chips').innerHTML=picked.map(e=>`<button class="chip" data-id="${e.id}">${e.time} · ${e.artist} ×</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{state.picked.delete(b.dataset.id);save();render()});const lo=915,hi=1500,last=picked.at(-1)?.end??lo;$('#progress').style.width=`${Math.max(0,Math.min(100,(last-lo)/(hi-lo)*100))}%`}
function save(){localStorage.setItem('tsp-day2',JSON.stringify([...state.picked]))}function reset(){state.picked.clear();save();render()}
fetch('data/schedule.json').then(r=>r.json()).then(data=>{build(data);render();$('#reset').onclick=reset;$('#clear').onclick=reset}).catch(()=>$('#timeline').textContent='Schedule gagal dimuat.');
window.__planner={state,render};
// ponytail: venue movement time is not encoded because source poster provides set times only; add walking buffers when venue map exists.

// Compatibility for browsers without Object.groupBy.
if(!Object.groupBy)Object.groupBy=(xs,fn)=>xs.reduce((o,x)=>(o[fn(x)]??=[],o[fn(x)].push(x),o),{});